name: Setup and Test Next.js App

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # or your preferred version
          cache: 'npm'

      - name: 📦 Installing test dependencie 

        run: |
         npm install --save-dev \
         jest \
         @testing-library/react \
         @testing-library/jest-dom \
         @testing-library/user-event \
         jest-environment-jsdom

         echo "✅ Test dependencies installed successfully."

      - name: 📦 Install project dependencies
        run: npm ci

     

      - name: ✅ Run Jest tests
        run: npm test
