name: Extract ZIP file

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  extract-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in repo root (before extraction)
        run: ls -lha

      - name: Extract ZIP file into repository root
        run: |
          unzip -o phaglp-platform28012026-master.zip -d ./
          echo "Zip file extracted in repository root."

      - name: List files in repo root (after extraction)
        run: ls -lha

      # Optional: Upload the extracted files as an artifact
      - name: Upload all extracted files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted-zip
          path: ./
